### ISSUE TITLE
when i run it it give me some errors

### ISSUE THREAD

**Issue by kaa3211** [georgGrankvist/BSCTokenScanner#2]
Hi
when i try to run it give me this errors in terminal:

PS C:\Users\96658> & "C:/Program Files/Python310/python.exe" "c:/Users/96658/Desktop/Coding Project/Bsc_Contract_Scraper.py"
Traceback (most recent call last):
  File "c:\Users\96658\Desktop\Coding Project\Bsc_Contract_Scraper.py", line 33, in <module>
    browser = uc.Chrome(use_subprocess=True,options=options)
  File "C:\Users\96658\AppData\Roaming\Python\Python310\site-packages\undetected_chromedriver\__init__.py", line 431, in __init__     
    super(Chrome, self).__init__(
  File "C:\Users\96658\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\chrome\webdriver.py", line 80, in __init__   
    super().__init__(
  File "C:\Users\96658\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\chromium\webdriver.py", line 104, in __init__
    super().__init__(
  File "C:\Users\96658\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 286, in __init__  
    self.start_session(capabilities, browser_profile)
  File "C:\Users\96658\AppData\Roaming\Python\Python310\site-packages\undetected_chromedriver\__init__.py", line 693, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "C:\Users\96658\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 378, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\96658\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "C:\Users\96658\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:7283
from unknown error: unable to discover open pages
Stacktrace:
Backtrace:
        GetHandleVerifier [0x00FC8893+48451]
        (No symbol) [0x00F5B8A1]
        (No symbol) [0x00E65058]
        (No symbol) [0x00E85C39]
        (No symbol) [0x00E80151]
        (No symbol) [0x00E7FF31]
        (No symbol) [0x00EB0798]
        (No symbol) [0x00EB047C]
        (No symbol) [0x00EAA0B6]
        (No symbol) [0x00E87E08]
        (No symbol) [0x00E88F2D]
        GetHandleVerifier [0x01228E3A+2540266]
        GetHandleVerifier [0x01268959+2801161]
        GetHandleVerifier [0x0126295C+2776588]
        GetHandleVerifier [0x01052280+612144]
        (No symbol) [0x00F64F6C]
        (No symbol) [0x00F611D8]
        (No symbol) [0x00F612BB]
        (No symbol) [0x00F54857]
        BaseThreadInitThunk [0x759500C9+25]
        RtlGetAppContainerNamedObjectPath [0x77617B4E+286]
        RtlGetAppContainerNamedObjectPath [0x77617B1E+238]

could you help me resolve it
and thank you  for your good working

**Comment by kaa3211** [comment]
PS C:\Users\96658> & "C:/Program Files/Python310/python.exe" "c:/Users/96658/Desktop/Coding Project/Bsc_Contract_Scraper.py"
Traceback (most recent call last):
  File "c:\Users\96658\Desktop\Coding Project\Bsc_Contract_Scraper.py", line 31, in <module>
    options.addArguments("--headless=new"); 
AttributeError: 'ChromeOptions' object has no attribute 'addArguments'. Did you mean: 'add_argument'?

**Comment by georgGrankvist** [comment]
> PS C:\Users\96658> & "C:/Program Files/Python310/python.exe" "c:/Users/96658/Desktop/Coding Project/Bsc_Contract_Scraper.py"
> Traceback (most recent call last):
> File "c:\Users\96658\Desktop\Coding Project\Bsc_Contract_Scraper.py", line 31, in 
> options.addArguments("--headless=new");
> AttributeError: 'ChromeOptions' object has no attribute 'addArguments'. Did you mean: 'add_argument'?

Yes, give that a go.

**Comment by kaa3211** [comment]
> has

Thank you sir for your response

I tried it and it is still not working

Terminal give me this result 

I don't know where is the problem?!

Maybe because deferent version of selenium??! Or version of UC?!

**Comment by kaa3211** [comment]
> PS C:\Users\96658> & "C:/Program Files/Python310/python.exe" "c:/Users/96658/Desktop/Coding Project/Bsc_Contract_Scraper.py"
> Traceback (most recent call last):
>   File "c:\Users\96658\Desktop\Coding Project\Bsc_Contract_Scraper.py", line 31, in <module>
>     options.addArguments("--headless=new"); 
> AttributeError: 'ChromeOptions' object has no attribute 'addArguments'. Did you mean: 'add_argument'?


Thank you sir for your response

I tried it and it is still not working

Terminal give me this result

I don't know where is the problem?!

Maybe because deferent version of selenium??! Or version of UC?!
